name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, major, pre)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - pre

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Deps
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm test -- --run

      - name: Setup Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update version in package.json
        id: version
        run: |
          git add -A
          git commit -m "chore: pre-release build [skip ci]" || echo "No changes to commit"
          if [ "${{ github.event.inputs.release_type }}" = "pre" ]; then
            npm version prerelease --preid=beta -m "chore(release): %s [skip ci]"
          else
            npm version ${{ github.event.inputs.release_type }} -m "chore(release): %s [skip ci]"
          fi

      - name: Get package version
        id: get_version
        run: |
          version=$(npm pkg get version | tr -d '"')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Push commit e tag
        run: |
          git push origin main --follow-tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          name: "Release v${{ steps.version.outputs.version }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
